on:
  workflow_dispatch:

jobs:
  webscreenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - name: install noto font
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto
      - name: npm install
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - uses: actions/upload-artifact@v3
        with:
          name: schedule
          path: ./cypress/snapshots/actual/spec.cy.ts
      - uses: actions/upload-artifact@v3
        with:
          name: video
          path: ./cypress/videos
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: downloads
          path: ./cypress/downloads
          retention-days: 1
