on:
  workflow_dispatch:
  schedule:
    # 日本時間で毎日18時に実行
    - cron: "0 0 25 * *"

jobs:
  send-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.40'
      - name: install noto font
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - uses: actions/upload-artifact@v3
        with:
          name: schedule
          path: ./cypress/snapshots/actual/spec.cy.ts
      - uses: actions/upload-artifact@v3
        with:
          name: video
          path: ./cypress/videos
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: downloads
          path: ./cypress/downloads
          retention-days: 1
      - name: send slack
        env:
            SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: deno run --allow-net --allow-env --allow-read sendSlack.ts